import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { getLocalStorage, setLocalStorage } from '../lib/storage_helper'

// declare global {
//   interface Window {
//       gtag: (...args: any[]) => void;
//   }
// }


export default function Home() {
  const [cookieConsent, setCookieConsent] = useState(false);

  useEffect(() => {
    const storedCookieConsent = getLocalStorage("cookie_consent", null);
    console.log("Stored Cookie Consent:", storedCookieConsent);
    setCookieConsent(storedCookieConsent);
  }, [setCookieConsent]);

  useEffect(() => {
    // if (typeof window !== 'undefined' && typeof window.gtag === 'function') {
      const newValue = cookieConsent ? 'granted' : 'denied';
      console.log("Setting cookie consent to:", newValue);
      

     window.gtag('consent', 'update', {
        'analytics_storage': newValue,
      });

      setLocalStorage("cookie_consent", cookieConsent);
      
      // For Testing
      console.log("Cookie Consent (final):", cookieConsent);
    // } else {
    //   console.log("gtag is not available or window is undefined");
    // }
  }, [cookieConsent]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ display: cookieConsent != null ? "none" : "flex", 
              margin: "2.5rem auto", 
              maxWidth: "max-content", 
              position: "fixed", 
              bottom: 0, 
              left: 0, 
              right: 0, 
              padding: "0.75rem 1rem", 
              justifyContent: "space-between", 
              alignItems: "center", 
              flexDirection: "column", 
              gap: "1rem", 
              backgroundColor: "#4B5563", // bg-gray-700
              borderRadius: "0.5rem", 
              boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)" }}>

        <div className='text-center'>
          <Link href="/info/cookies">
            <p>We use <span className='font-bold text-sky-400'>cookies</span> on our site.</p>
          </Link>
        </div>

        <div className='flex gap-2'>
          <button 
            className='px-5 py-2 text-gray-300 rounded-md border-gray-900' 
            onClick={() => setCookieConsent(false)}>
            Decline
          </button>
          <button 
            className='bg-gray-900 px-5 py-2 text-white rounded-lg' 
            onClick={() => setCookieConsent(true)}>
            Allow Cookies
          </button>
        </div>   
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
