// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
// import Link from 'next/link'
// import { useEffect, useState } from 'react'
// import { getLocalStorage, setLocalStorage } from '../lib/storage_helper'

// // declare global {
// //   interface Window {
// //       gtag: (...args: any[]) => void;
// //   }
// // }


// export default function Home() {
//   const [cookieConsent, setCookieConsent] = useState(false);

//   useEffect(() => {
//     const storedCookieConsent = getLocalStorage("cookie_consent", null);
//     console.log("Stored Cookie Consent:", storedCookieConsent);
//     setCookieConsent(storedCookieConsent);
//   }, [setCookieConsent]);

//   useEffect(() => {
//     // if (typeof window !== 'undefined' && typeof window.gtag === 'function') {
//       const newValue = cookieConsent ? 'granted' : 'denied';
//       console.log("Setting cookie consent to:", newValue);
      

//      window.gtag('consent', 'update', {
//         'analytics_storage': newValue,
//       });

//       setLocalStorage("cookie_consent", cookieConsent);
      
//       // For Testing
//       console.log("Cookie Consent (final):", cookieConsent);
//     // } else {
//     //   console.log("gtag is not available or window is undefined");
//     // }
//   }, [cookieConsent]);

//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <div style={{ display: cookieConsent != null ? "none" : "flex", 
//               margin: "2.5rem auto", 
//               maxWidth: "max-content", 
//               position: "fixed", 
//               bottom: 0, 
//               left: 0, 
//               right: 0, 
//               padding: "0.75rem 1rem", 
//               justifyContent: "space-between", 
//               alignItems: "center", 
//               flexDirection: "column", 
//               gap: "1rem", 
//               backgroundColor: "#4B5563", // bg-gray-700
//               borderRadius: "0.5rem", 
//               boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)" }}>

//         <div className='text-center'>
//           <Link href="/info/cookies">
//             <p>We use <span className='font-bold text-sky-400'>cookies</span> on our site.</p>
//           </Link>
//         </div>

//         <div className='flex gap-2'>
//           <button 
//             className='px-5 py-2 text-gray-300 rounded-md border-gray-900' 
//             onClick={() => setCookieConsent(false)}>
//             Decline
//           </button>
//           <button 
//             className='bg-gray-900 px-5 py-2 text-white rounded-lg' 
//             onClick={() => setCookieConsent(true)}>
//             Allow Cookies
//           </button>
//         </div>   
//       </div>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }

// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
// import Link from 'next/link'
// import { useEffect, useState } from 'react'
// import { getLocalStorage, setLocalStorage } from '../lib/storage_helper'

// export default function Home() {
//   const [cookieConsent, setCookieConsent] = useState(null);

//   useEffect(() => {
//     const storedCookieConsent = getLocalStorage("cookie_consent", null);
//     setCookieConsent(storedCookieConsent);
//   }, []);

//   useEffect(() => {
//     if (cookieConsent) {
//       // Load Google Analytics script after consent is granted
//       const script = document.createElement('script');
//       script.src = `https://www.googletagmanager.com/gtag/js?id=YOUR_GA_TRACKING_ID`;
//       script.async = true;
//       document.head.appendChild(script);

//       script.onload = () => {
//         window.dataLayer = window.dataLayer || [];
//         function gtag(){ dataLayer.push(arguments); }
//         window.gtag = gtag;
//         gtag('js', new Date());
//         gtag('config', 'YOUR_GA_TRACKING_ID', {
//           page_path: window.location.pathname,
//         });
//       };

//       // Store consent in local storage
//       setLocalStorage("cookie_consent", true);
//     }
//   }, [cookieConsent]);

//   const handleConsent = (consent) => {
//     setCookieConsent(consent);
//     if (!consent) {
//       setLocalStorage("cookie_consent", false);
//     }
//   };

//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>
//       </main>

//       <div style={{ display: cookieConsent != null ? "none" : "flex", 
//                     margin: "2.5rem auto", 
//                     maxWidth: "max-content", 
//                     position: "fixed", 
//                     bottom: 0, 
//                     left: 0, 
//                     right: 0, 
//                     padding: "0.75rem 1rem", 
//                     justifyContent: "space-between", 
//                     alignItems: "center", 
//                     flexDirection: "column", 
//                     gap: "1rem", 
//                     backgroundColor: "#4B5563", 
//                     borderRadius: "0.5rem", 
//                     boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)" }}>
//         <div style={{ textAlign: "center" }}>
//           <Link href="/info/cookies">
//             <p>We use <span style={{ fontWeight: "bold", color: "#38BDF8" }}>cookies</span> on our site.</p>
//           </Link>
//         </div>

//         <div style={{ display: "flex", gap: "0.5rem" }}>
//           <button 
//             style={{ padding: "0.5rem 1.25rem", color: "#D1D5DB", backgroundColor: "#1F2937", borderRadius: "0.375rem", border: "1px solid #1F2937" }} 
//             onClick={() => handleConsent(false)}>
//             Decline
//           </button>
//           <button 
//             style={{ padding: "0.5rem 1.25rem", color: "#FFFFFF", backgroundColor: "#000000", borderRadius: "0.5rem" }} 
//             onClick={() => handleConsent(true)}>
//             Allow Cookies
//           </button>
//         </div>   
//       </div>

//       <footer className={styles.footer}>
//         {/* Footer content */}
//       </footer>
//     </div>
//   )
// }
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { getLocalStorage, setLocalStorage } from '../lib/storage_helper';

export default function Home() {
  const [cookieConsent, setCookieConsent] = useState(null);

  useEffect(() => {
    const storedCookieConsent = getLocalStorage('cookie_consent', null);
    if (storedCookieConsent !== null) {
      setCookieConsent(storedCookieConsent);
    }
  }, []);

  useEffect(() => {
    document.cookie.split(';').forEach((cookie) => {
      const cookieName = cookie.split('=')[0].trim();
      if (cookieName.startsWith('_ga') || cookieName.startsWith('GA')) {
        document.cookie = `${cookieName}=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;`;
      }
    });

    
    if (cookieConsent !== null) {
      setLocalStorage('cookie_consent', cookieConsent);
     

      if (cookieConsent && typeof window.gtag === 'undefined') {
        // Create a script element and load the GA script
        const script = document.createElement('script');
        script.src = `https://www.googletagmanager.com/gtag/js?id=G-B71N5R0MH5`;
        script.async = true;
        document.head.appendChild(script);

        // Initialize gtag once the script is loaded
        script.onload = () => {
          window.dataLayer = window.dataLayer || [];
          function gtag() {
            window.dataLayer.push(arguments);
          }
          window.gtag = gtag;

          gtag('js', new Date());
          gtag('config', 'G-B71N5R0MH5', {
            page_path: window.location.pathname,
          });
        };
      } else if (!cookieConsent) {
        console.log("asd")
        // If consent is denied, remove any GA cookies
        document.cookie.split(';').forEach((cookie) => {
          const cookieName = cookie.split('=')[0].trim();
          if (cookieName.startsWith('_ga') || cookieName.startsWith('GA')) {
            document.cookie = `${cookieName}=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;`;
          }
        });
      }
    }
  }, [cookieConsent]);

  const handleConsent = (consent) => {
    setCookieConsent(consent);
  };

  return (
    <div>
      <Head>
        <title>Your Site</title>
      </Head>

      <main>
        <h1>Welcome to Your Site</h1>
      </main>

      {cookieConsent === null && (
        <div
          style={{
            display: 'flex',
            margin: '2.5rem auto',
            maxWidth: 'max-content',
            position: 'fixed',
            bottom: 0,
            left: 0,
            right: 0,
            padding: '0.75rem 1rem',
            justifyContent: 'space-between',
            alignItems: 'center',
            flexDirection: 'column',
            gap: '1rem',
            backgroundColor: '#4B5563',
            borderRadius: '0.5rem',
            boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
          }}
        >
          <div style={{ textAlign: 'center' }}>
            We use cookies on our site.
          </div>

          <div style={{ display: 'flex', gap: '0.5rem' }}>
            <button
              style={{
                padding: '0.5rem 1.25rem',
                color: '#D1D5DB',
                backgroundColor: '#1F2937',
                borderRadius: '0.375rem',
                border: '1px solid #1F2937',
              }}
              onClick={() => handleConsent(false)}
            >
              Decline
            </button>
            <button
              style={{
                padding: '0.5rem 1.25rem',
                color: '#FFFFFF',
                backgroundColor: '#000000',
                borderRadius: '0.5rem',
              }}
              onClick={() => handleConsent(true)}
            >
              Allow Cookies
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
